export const STUDIO_HTML = String.raw`<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Video Importer Studio</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#eee;background:#0a0a0c}*{box-sizing:border-box}body{margin:0}header{padding:24px 5%;border-bottom:1px solid #25252c;background:#111116}main{width:min(1400px,92%);margin:24px auto}.grid{display:grid;grid-template-columns:360px 1fr;gap:20px}.card{background:#15151b;border:1px solid #292933;border-radius:14px;padding:18px;margin-bottom:18px}h1,h2{margin-top:0}label{display:block;color:#aaa;font-size:13px;margin:10px 0 5px}input,select,textarea,button{width:100%;padding:10px;border-radius:8px;border:1px solid #353541;background:#0e0e12;color:#eee}textarea{min-height:110px}button{background:#7357ff;border:0;font-weight:700;cursor:pointer;margin-top:12px}.secondary{background:#292933}.row{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.toolbar{display:flex;gap:10px;align-items:end}.toolbar>*{flex:1}.status{padding:12px;border-radius:8px;background:#22222a;margin:12px 0;white-space:pre-wrap}.videos{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}.video{border:1px solid #30303a;border-radius:10px;overflow:hidden;background:#101014}.video img{width:100%;aspect-ratio:16/9;object-fit:cover}.video div{padding:10px}.video input{width:auto}.muted{color:#8d8d99;font-size:12px}@media(max-width:850px){.grid{grid-template-columns:1fr}}
</style></head><body>
<header><h1>Video Importer Studio</h1><div class="muted">Busca, edita con CSV y publica en distintos sitios desde un solo panel.</div></header>
<main><div class="grid"><aside>
<section class="card"><h2>Sitios</h2><label>Perfil</label><select id="profile"></select>
<label>Nombre</label><input id="pname" placeholder="Zorritas local">
<label>Tipo</label><select id="adapter"><option value="zorritas-sqlite">SQLite / Zorritas</option><option value="wordpress-rest">WordPress REST</option><option value="json-export">Exportar JSON</option></select>
<label>URL del sitio</label><input id="baseUrl" placeholder="https://misitio.com">
<label>Ruta SQLite o carpeta de exportación</label><input id="target" placeholder="C:\ruta\migration.db">
<div class="row"><div><label>Usuario WP</label><input id="username"></div><div><label>Contraseña de aplicación</label><input id="password" type="password"></div></div>
<label>Plantilla de contenido</label><textarea id="template">{embed_code}

{description}</textarea><button onclick="saveProfile()">Guardar perfil</button></section>
<section class="card"><h2>CSV</h2><input id="csvFile" type="file" accept=".csv"><button class="secondary" onclick="downloadTemplate()">Descargar plantilla</button><button onclick="previewCsv()">Aplicar CSV</button></section>
</aside><div>
<section class="card"><h2>Buscar</h2><div class="toolbar"><div><label>Fuente</label><select id="source"><option>xvideos</option><option>pornhub</option><option>redtube</option><option>xhamster</option><option>youporn</option></select></div><div><label>Palabras</label><input id="keywords"></div><div><label>Página</label><input id="page" type="number" value="1" min="1"></div><button onclick="search()">Buscar</button></div></section>
<div id="status" class="status">Listo.</div><section class="card"><div class="toolbar"><h2>Resultados</h2><button onclick="publish()">Publicar seleccionados</button></div><div id="videos" class="videos"></div></section>
</div></div></main><script>
let profiles=[],videos=[],items=[];
const $=id=>document.getElementById(id); const api=async(url,options={})=>{const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const d=await r.json();if(!r.ok)throw Error(d.error||r.statusText);return d};
async function loadProfiles(){profiles=await api('/api/profiles');$('profile').innerHTML='<option value="">Seleccionar…</option>'+profiles.map(p=>'<option value="'+p.id+'">'+escapeHtml(p.name)+'</option>').join('')}
async function saveProfile(){const adapter=$('adapter').value,target=$('target').value;const p={id:$('profile').value,name:$('pname').value,adapter,baseUrl:$('baseUrl').value,username:$('username').value,applicationPassword:$('password').value||undefined,contentTemplate:$('template').value,defaultStatus:'draft',databasePath:adapter==='zorritas-sqlite'?target:undefined,outputDirectory:adapter==='json-export'?target:undefined};await api('/api/profiles',{method:'POST',body:JSON.stringify(p)});await loadProfiles();setStatus('Perfil guardado')}
$('profile').onchange=()=>{const p=profiles.find(x=>x.id===$('profile').value);if(!p)return;$('pname').value=p.name;$('adapter').value=p.adapter;$('baseUrl').value=p.baseUrl||'';$('target').value=p.databasePath||p.outputDirectory||'';$('username').value=p.username||'';$('template').value=p.contentTemplate||'{embed_code}\\n\\n{description}'}
async function search(){setStatus('Buscando…');const d=await api('/api/search',{method:'POST',body:JSON.stringify({sourceId:$('source').value,keywords:$('keywords').value,page:+$('page').value})});videos=d.videos;items=videos.map(video=>({video,title:video.title,description:'',tags:video.tags,status:'draft'}));render();setStatus(d.count+' videos encontrados')}
function render(){ $('videos').innerHTML=items.map((x,i)=>'<article class="video"><img src="'+escapeHtml(x.video.thumbnail)+'"><div><label><input type="checkbox" data-select="'+i+'" checked> Seleccionar</label><input data-title="'+i+'" value="'+escapeHtml(x.title||'')+'"><textarea data-description="'+i+'" placeholder="Descripción">'+escapeHtml(x.description||'')+'</textarea><div class="muted">'+escapeHtml(x.video.sourceId+' · '+x.video.videoId)+'</div></div></article>').join('')}
async function previewCsv(){const file=$('csvFile').files[0];if(!file)return setStatus('Selecciona un CSV');const d=await api('/api/csv-preview',{method:'POST',body:JSON.stringify({csv:await file.text(),videos})});items=d.items;render();setStatus(d.rows+' filas CSV preparadas')}
async function publish(){const id=$('profile').value;if(!id)return setStatus('Selecciona un perfil');document.querySelectorAll('[data-title]').forEach(e=>items[+e.dataset.title].title=e.value);document.querySelectorAll('[data-description]').forEach(e=>items[+e.dataset.description].description=e.value);const selected=items.filter((_,i)=>document.querySelector('[data-select="'+i+'"]').checked);setStatus('Publicando '+selected.length+'…');const d=await api('/api/publish',{method:'POST',body:JSON.stringify({profileId:id,items:selected})});setStatus('Creados/duplicados: '+d.imported.length+'\\nErrores: '+d.errors.length+(d.errors.length?'\\n'+d.errors.map(e=>e.title+': '+e.error).join('\\n'):''))}
function downloadTemplate(){location.href='/api/csv-template'} function setStatus(s){$('status').textContent=s} function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))} loadProfiles();
</script></body></html>`
