import { NextResponse, type NextRequest } from 'next/server'

// Legacy WP date-prefixed URLs → canonical /slug
// Examples:
//   /2023/06/my-post   → /my-post
//   /2023/06/my-post/  → /my-post
const DATE_PREFIX_RE = /^\/(\d{4})\/(\d{2})\/([^\/]+)\/?$/

// Post-duplicate redirects from migration.db (one entry per duplicate slug).
// Generated by: python -m src.cli export-redirects
// File: _migration_workspace/exports/next-redirects.json
//
// At build/dev time we read this JSON synchronously. The file is small (~6,305
// entries, ~600 KB). Next.js middleware runs in the Edge runtime — no Node
// modules. We use Web APIs only.

// Inline static redirect map — the entries are bundled at build time.
// To regenerate after `generate-redirects`, run: python -m src.cli export-redirects
//   then copy _migration_workspace/exports/next-redirects.json to
//        zor3convertido/webapp/redirects.data.json
// and update the import below.
import redirectsData from './redirects.data.json'

type Redirect = { source: string; destination: string; statusCode: number }
const REDIRECTS: ReadonlyArray<Redirect> = redirectsData as Redirect[]

const REDIRECT_MAP: Map<string, { dest: string; status: number }> = new Map(
  REDIRECTS.map(r => [r.source, { dest: r.destination, status: r.statusCode || 301 }])
)

export function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl

  // Protect the administration area with HTTP Basic Auth. EasyPanel can
  // provide these variables per site without changing the reusable theme.
  if (pathname.startsWith('/admin') || pathname.startsWith('/api/admin')) {
    const user = process.env.ADMIN_USER
    const password = process.env.ADMIN_PASSWORD
    const authorization = req.headers.get('authorization')
    let valid = false
    if (user && password && authorization?.startsWith('Basic ')) {
      try {
        const decoded = atob(authorization.slice(6))
        valid = decoded === `${user}:${password}`
      } catch {}
    }
    if (!valid) {
      return new NextResponse('Autenticación requerida', {
        status: 401,
        headers: { 'WWW-Authenticate': 'Basic realm="Administración", charset="UTF-8"' },
      })
    }
  }

  // 1) Date-prefixed legacy WP URLs
  const m = pathname.match(DATE_PREFIX_RE)
  if (m) {
    const slug = m[3]
    const url = req.nextUrl.clone()
    url.pathname = `/${slug}`
    return NextResponse.redirect(url, 301)
  }

  // 2) Post-duplicate redirects from migration.db
  const hit = REDIRECT_MAP.get(pathname)
  if (hit) {
    const url = req.nextUrl.clone()
    url.pathname = hit.dest
    return NextResponse.redirect(url, hit.status)
  }

  return NextResponse.next()
}

export const config = {
  matcher: [
    '/:year(\\d{4})/:month(\\d{2})/:slug',
    '/:year(\\d{4})/:month(\\d{2})/:slug/',
    // Match everything except static assets so we can apply redirects broadly.
    '/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml).*)',
  ],
}
